In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.metrics import classification_report,confusion_matrix

F:\ANACONDARAJ\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
F:\ANACONDARAJ\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
df=pd.read_csv('C:\\Users\\User\\Downloads\\glass.csv')

In [3]:
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [4]:
X=df.drop('Type',axis=1)
y=df['Type']
scaler=StandardScaler()

0    1
1    1
2    1
3    1
4    1
Name: Type, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=101)

In [8]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [9]:
X_test.shape

(65, 9)

In [10]:
X_train.shape

(149, 9)

In [13]:
from sklearn.model_selection import GridSearchCV

In [15]:
parameters=[{'n_neighbors':[5,10,15],'weights': ['uniform']},
           {'n_neighbors':[5,10,15],'weights': ['distance']}]

In [16]:
grid_search=GridSearchCV(estimator=knn,param_grid=parameters,n_jobs=-1,cv=10,scoring='accuracy')
grid_search.fit(X_train,y_train)

F:\ANACONDARAJ\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=-1,
             param_grid=[{'n_neighbors': [5, 10, 15], 'weights': ['uniform']},
                         {'n_neighbors': [5, 10, 15], 'weights': ['distance']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [17]:
grid_search.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='distance')

In [18]:
grid_search.best_params_

{'n_neighbors': 5, 'weights': 'distance'}

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
knn=KNeighborsClassifier(n_neighbors= 5, weights= 'distance')
knn.fit(X_train,y_train)
pred_knn=knn.predict(X_test)
print(classification_report(y_test,pred_knn))
print(confusion_matrix(y_test,pred_knn))

              precision    recall  f1-score   support

           1       0.76      0.81      0.79        27
           2       0.58      0.88      0.70        16
           3       1.00      0.11      0.20         9
           5       1.00      0.80      0.89         5
           6       0.80      1.00      0.89         4
           7       1.00      0.50      0.67         4

    accuracy                           0.72        65
   macro avg       0.86      0.68      0.69        65
weighted avg       0.78      0.72      0.69        65

[[22  5  0  0  0  0]
 [ 1 14  0  0  1  0]
 [ 5  3  1  0  0  0]
 [ 0  1  0  4  0  0]
 [ 0  0  0  0  4  0]
 [ 1  1  0  0  0  2]]


In [20]:
from xgboost import XGBClassifier
xgb=XGBClassifier()
xgb.fit(X_train,y_train)
pred_xgb=xgb.predict(X_test)
print(classification_report(y_test,pred_xgb))
print(confusion_matrix(y_test,pred_xgb))

              precision    recall  f1-score   support

           1       0.75      0.89      0.81        27
           2       0.57      0.75      0.65        16
           3       1.00      0.11      0.20         9
           5       0.71      1.00      0.83         5
           6       1.00      0.50      0.67         4
           7       1.00      0.50      0.67         4

    accuracy                           0.71        65
   macro avg       0.84      0.62      0.64        65
weighted avg       0.77      0.71      0.67        65

[[24  3  0  0  0  0]
 [ 3 12  0  1  0  0]
 [ 3  5  1  0  0  0]
 [ 0  0  0  5  0  0]
 [ 1  0  0  1  2  0]
 [ 1  1  0  0  0  2]]


In [21]:
df1=pd.read_csv('C:\\Users\\User\\Downloads\\zoo.csv')

In [22]:
df1.head()

animal name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   type  
0     1  
1     1  
2     4  
3     1  
4     1

In [27]:
df1['type'].unique()

array([1, 4, 2, 7, 6, 5, 3], dtype=int64)

In [29]:
df1['animal name'].nunique()

100

In [30]:
len(df1)

101

In [32]:
df1=df1.drop('animal name',axis=1)

In [33]:
X=df1.drop('type',axis=1)
y=df1['type']

In [35]:
y.head()

0    1
1    1
2    4
3    1
4    1
Name: type, dtype: int64

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [37]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [38]:
X_train.shape

(70, 16)

In [39]:
X_test.shape

(31, 16)

In [40]:
grid_search=GridSearchCV(estimator=knn,param_grid=parameters,n_jobs=-1,cv=10,scoring='accuracy')
grid_search.fit(X_train,y_train)

F:\ANACONDARAJ\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='distance'),
             iid='warn', n_jobs=-1,
             param_grid=[{'n_neighbors': [5, 10, 15], 'weights': ['uniform']},
                         {'n_neighbors': [5, 10, 15], 'weights': ['distance']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [41]:
grid_search.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='distance')

In [42]:
grid_search.best_params_

{'n_neighbors': 5, 'weights': 'distance'}

In [43]:
knn=KNeighborsClassifier(n_neighbors= 5, weights= 'distance')
knn.fit(X_train,y_train)
pred_knn=knn.predict(X_test)
print(classification_report(y_test,pred_knn))
print(confusion_matrix(y_test,pred_knn))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        10
           2       0.91      1.00      0.95        10
           3       0.00      0.00      0.00         1
           4       1.00      1.00      1.00         4
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         4

    accuracy                           0.97        31
   macro avg       0.84      0.86      0.85        31
weighted avg       0.94      0.97      0.95        31

[[10  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0]
 [ 0  1  0  0  0  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  4]]


F:\ANACONDARAJ\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
